[pytest]
markers =
    markers_demo: demo for markers - pytest course with Artem Istranin
    critical: set of tests that is crucial to pass for deployment (run before every commit)
    with_transactions: add transactions to tracker from conftest.py
    with_categories: add categories to tracker from conftest.py

addopts = --verbose

usefixtures = clean_db